language: node_js

sudo: false

node_js:
  - "10"

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master

before_install:
  - export TZ=Asia/Shanghai

script:
  - yarn run build

after_success:
  - cd docs/.vuepress/dist
  - git add -A
  - git commit -m "deploy at `date +\"%Y-%m-%d %H:%M:%S\"`"
  - git push --force --quiet "git@github.com:essencemike/vp-blog.git" master:gh-pages